# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170331_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=64),
        ),
    ]
